name: Examples Checks
on:
  pull_request:

jobs:
  validate-terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.21'
      - run: go build -o terraform-plugin-dir/terraform-provider-aws_v99.99.99_x5 .
      - run: |
          mkdir -p ~/.terraform.d/plugins/registry.terraform.io/hashicorp/aws/99.99.99/linux_amd64/
          cp terraform-plugin-dir/terraform-provider-aws_v99.99.99_x5 ~/.terraform.d/plugins/registry.terraform.io/hashicorp/aws/99.99.99/linux_amd64/
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - run: cd examples/basic && terraform init && terraform validate
